# Generated by Django 4.2.1 on 2023-05-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('teacher', models.TextField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('location', models.TextField(max_length=200)),
            ],
        ),
    ]
