# Generated by Django 4.2.1 on 2023-05-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_location_alter_course_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='participant',
            field=models.ManyToManyField(blank=True, null=True, to='bookings.participant'),
        ),
    ]
