# Generated by Django 4.2.1 on 2023-06-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_course_date_course_organizer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.TextField(default='3', max_length=5),
            preserve_default=False,
        ),
    ]
