# Generated by Django 4.2.1 on 2023-06-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_course_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hours',
            field=models.TextField(max_length=20),
        ),
    ]
